[package]
name = "monitoring-rs"
version = "0.1.0"
authors = ["Chris Connelly <chris@connec.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.15"
