# docker-compose.yaml
version: '3.8'
services:
  monitoring:
    build: .
    image: registry.digitalocean.com/connec-co-uk/monitoring-rs:latest
    volumes:
    - logs:/var/log/containers
    environment:
    - RUST_LOG=monitoring_rs=debug
    ports:
    - 8000:8000

  test:
    build:
      context: .
      target: builder
    command: [cargo, test, --release]

  lint:
    build:
      context: .
      target: builder
    command: [cargo, clippy, --tests]

  writer:
    image: alpine
    volumes:
    - logs:/var/log/containers
    command:
    - sh
    - -c
    - while true ; do date ; sleep 1 ; done | cat >> /var/log/containers/writer.log

  inspect:
    image: alpine
    volumes:
    - logs:/var/log/containers
    command:
    - sh
    - -c
    - cat /var/log/containers/*

  rotate:
    image: alpine
    volumes:
    - logs:/var/log/containers
    command:
    - sh
    - -c
    - |
      apk add --no-cache logrotate
      cat <<EOF > test.config
      /var/log/containers/writer.log {
        copytruncate
        size 1
      }
      EOF
      logrotate --verbose test.config

volumes:
  logs:
