# deployment/kubernetes.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-rs
  namespace: monitoring-rs
imagePullSecrets:
- name: registry-connec-co-uk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-rs
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-rs
subjects:
- kind: ServiceAccount
  name: monitoring-rs
  namespace: monitoring-rs
roleRef:
  kind: ClusterRole
  name: monitoring-rs
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-rs-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-rs
  labels:
    app: monitoring-rs
spec:
  selector:
    matchLabels:
      app: monitoring-rs
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring-rs
    spec:
      serviceAccountName: monitoring-rs
      containers:
      - name: monitoring-rs
        image: $DOCKER_DIGEST
        volumeMounts:
        - name: data
          mountPath: /.data
          subPath: .data
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: monitoring-rs-data
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
          type: Directory
